        </main>
        <footer class="container my-5">
            <div class="row justify-content-center">
                <div class="col-md-6" align="center">
                    <p class="small text-muted">&copy; 2017-<?= htmlspecialchars( date("Y") ) ?> | Powered by Julio Cesar | All rights reserved.</p>
                    <a href="https://github.com/jys33/crud-postcode" target="_blank">
                        <img src="img/github-brands.svg" style="width: 24px; height: 24px; color: #c6cbd1;">
                    </a>
                </div>
            </div>
        </footer>
        <a class="cd-top js-cd-top" title="Subir">Top</a>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <!-- DataTables CDN-->
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

        <!-- Ejecuta la DataTable -->
        <script type="text/javascript" src="js/scripts.js"></script>
        <!--  -->
        <script type="text/javascript" src="js/chained-dropdown-list.js"></script>
    </body>
</html>