<section class="page-404">
    <div class="container">
    	<div class="row justify-content-center">
    		<div class="col-md-6 cold-md-offset-3" align="center">
    			<h1 class="display-1">Oops! <p class="emoticon"> :(</p></h1>
    			<h2 class="mb-4">404 - The Page can't be found</h2>
    			<form method="POST" action="index.php">
    				<button class="btn btn-lg btn-success">Volver al inicio</button>
    			</form>
    		</div>
    	</div>
    </div>
</section>
<style type="text/css">
	.page-404{
		margin-top: 50px;
        margin-bottom: 50px;
	}
    .page-404 .emoticon {
        font-family: sans-serif;
        font-size: 6rem;
    }
</style>