<section class="apology">
	<div class="row">
		<div class="col-md-12">
			<div class="text-center">
				<h1 class="display-1">
				    Sorry!
				</h1>
				<h2 class="mb-4">
					<?= htmlspecialchars($message) ?>
				</h2>
				<a class="btn btn-lg btn-success shadow-none" href="javascript:history.go(-1);">Back</a>
			</div>
		</div>
	</div>
</section>
<style type="text/css">
	.apology{
		margin-top: 100px;
		margin-bottom: 100px;
	}
</style>