<section class="error404">
    <div class="container">
    	<div class="row justify-content-center">
    		<div class="col-md-6 cold-md-offset-3" align="center">
    			<h1 class="display-1">Oops!</h1>
    			<h2 class="mb-4">404 - The Page can't be found</h2>
    			<form method="POST" action="index.php">
    				<button class="btn btn-lg btn-success shadow-none">Volver al inicio</button>
    			</form>
    		</div>
    	</div>
    </div>
</section>
<style type="text/css">
	.error404{
		margin-top: 100px;
        margin-bottom: 100px;
	}
</style>