<section class="mt-3">
	<div class="container">
		<div class="row">
			<div class="container container--login">
				<!-- <img class="img-fluid mx-auto d-block mb-5" style="width: 65px; height: 65px" src="" alt=""> -->
				<h1 class="mb-1 text-center" style="font-size: 34px">Establecer contraseña</h1>
				<p class="fs-14 text-muted text-center mb-5">Elija una nueva contraseña y nosotros nos encargaremos de todo lo demás.</p>
				<form id="" action="/change_password.php" method="POST">
					<div class="form-group">
						<label for="new_password">Nueva contraseña</label>
						<input type="password" name="new_password" id="new_password" class="form-control form-control-lg <?= empty($new_password_err) ? '' : 'is-invalid' ?>" size="20">
						<div class="invalid-feedback"><?= htmlspecialchars($new_password_err) ?></div>
					</div>
					<div class="form-group">
						<label for="new_password_confirm">Confirmar nueva contraseña</label>
						<input type="password" name="new_password_confirm" id="new_password_confirm" class="form-control form-control-lg <?= empty($new_password_confirm_err) ? '' : 'is-invalid' ?>" size="20">
						<div class="invalid-feedback"><?= htmlspecialchars($new_password_confirm_err) ?></div>
					</div>
					<button type="submit" class="btn btn-custom btn-lg btn-block mb-4">Guardar nueva contraseña</button>
				</form>
			</div>
		</div>
	</div>
</section>