<!-- Formulario de registro -->
<section class="my-4">
    <div class="container">
        <div class="row">
            <div class="container container--xs">
                <form class="" method="post" action="edit.php">
                    <h2 class="mb-1 text-center font-weight-normal">Actualizar usuario</h2>
                    <p class="fs-14 text-muted text-center mb-4">Por favor, si desea actualizar modifique sus datos.</p>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="firstname">Nombre <span class="required">*</span></label>
                            <input name="firstname" type="text" class="form-control form-control-lg <?= empty($firstname_err) ? '' : 'is-invalid' ?>" id="firstname" placeholder="Nombre" value="<?= htmlspecialchars( $firstname ) ?>" autofocus >
                            <div class="invalid-feedback"><?= htmlspecialchars($firstname_err) ?></div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="lastname">Apellido <span class="required">*</span></label>
                            <input name="lastname" type="text" class="form-control form-control-lg <?= empty($lastname_err) ? '' : 'is-invalid' ?>" id="lastname" placeholder="Apellido" value="<?= htmlspecialchars( $lastname ) ?>" >
                            <div class="invalid-feedback"><?= htmlspecialchars($lastname_err) ?></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="username">Usuario <span class="required">*</span></label>
                        <input name="username" type="text" class="form-control form-control-lg <?= empty($username_err) ? '' : 'is-invalid' ?>" id="username" placeholder="Usuario"
                        value="<?= htmlspecialchars( $username )?>" >
                        <div class="invalid-feedback"><?= htmlspecialchars($username_err) ?></div>
                    </div>
                    <!-- <div class="form-group">
                        <label for="useremail">Email <span class="required">*</span></label>
                        <input name="useremail" type="email" class="form-control form-control-lg <?= empty($useremail_err) ? '' : 'is-invalid' ?>" id="useremail" placeholder="Email"
                        value="<?= htmlspecialchars( $useremail ) ?>" >
                        <div class="invalid-feedback"><?= htmlspecialchars($useremail_err) ?></div>
                    </div> -->
                    <!-- <div class="form-group">
                        <label for="password">Contraseña <span class="required">*</span></label>
                        <input name="password" type="password" class="form-control form-control-lg <?= empty($password_err) ? '' : 'is-invalid' ?>" id="password" placeholder="Contraseña" >
                        <small id="emailHelp" class="form-text text-muted">Al menos 8 caracteres de longitud.</small>
                        <div class="invalid-feedback"><?= htmlspecialchars($password_err) ?></div>
                    </div> -->
                    <div class="form-group">
                        <label for="address">Domicilio <span class="required">*</span></label>
                        <input name="address" type="text" class="form-control form-control-lg <?= empty($address_err) ? '' : 'is-invalid' ?>" id="address" placeholder="Domicilio" value="<?= htmlspecialchars( $address ) ?>">
                        <div class="invalid-feedback"><?= htmlspecialchars($address_err) ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="provincia">Provincia <span class="required">*</span></label>
                            <select class="custom-select custom-select-lg d-block w-100 <?= empty($provincia_err) ? '' : 'is-invalid' ?>" name="provincia" id="province">
                                <option disabled selected>-- Seleccione una provincia --</option>
                              
                              <?php
                                foreach ($provincias as $key => $value) {
                                    echo '<option value="'. $value['provincia'] .'"';
                                    echo ($value['provincia'] == $provincia) ? 'selected' : '';
                                    echo  '>' . $value['provincia'] . '</option>';
                                }
                              ?>
                            </select>
                            <div class="invalid-feedback"><?= htmlspecialchars($provincia_err) ?></div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="localidad">Localidad <span class="required">*</span></label>
                            <select name="localidad" class="custom-select custom-select-lg d-block w-100" id="localidad" disabled>
                                
                            </select>
                            <small id="localidadHelp" class="form-text text-muted">No seleccionar si la localidad sigue siendo la misma.</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-block btn-success btn-lg shadow-none">Enviar</button>
                            </div>
                            <div class="col-md-6">
                                <a href="index.php" class="btn btn-block btn-light btn-lg shadow-none">Volver</a>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="user_id" value="<?= $user_id ?>">
                </form>
            </div>
        </div>
    </div>
</section>
