<section class="mt-5">
	<div class="container">
		<div class="row">
			<div class="container container--signup"><!--col-md-4 offset-md-4-->
				<h1 class="mb-1 text-center" style="font-size: 34px">Recuperar contraseña</h1>
				<p class="fs-14 text-muted text-center mb-5">Introduce tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.</p>
				<form action="/forgot_password.php" method="POST">
					<div class="form-group">
						<label for="email">Tu correo electrónico</label>
						<input type="email" name="useremail" id="useremail" class="form-control form-control-lg <?= empty($useremail_err) ? '' : 'is-invalid' ?>" autofocus placeholder="Ingrese su dirección de correo electrónico" value="<?= htmlspecialchars( $useremail ) ?>" size="20">
						<div class="invalid-feedback"><?= htmlspecialchars($useremail_err)  ?></div>
					</div>
					<button type="submit" class="btn btn-custom btn-block mb-4 btn-lg">Recuperar contraseña</button>
				</form>
				<p class="small text-center text-muted">¿Recuerdas tu contraseña? <a href="/">Inicia sesión</a></p>
			</div>
		</div>
	</div>
</section>