<section class="mt-4">
	<div class="container">
		<div class="row">
			<div class="container container--mini">
				<!-- <img class="img-fluid mx-auto d-block mb-5" style="width: 65px; height: 65px" src="" alt=""> -->
				<?php flash('flash_success'); flash('flash_error'); ?>
				<h1 class="mb-1 text-center" style="font-size: 34px">Inicia sesión</h1>
				<p class="fs-14 text-muted text-center mb-5">Complete sus datos para ingresar en la app.</p>
				<form name="loginform" id="loginform" action="/login.php" method="POST">
					<div class="form-group">
						<label for="email">Correo electrónico</label>
						<input type="email" name="email" class="form-control form-control-lg <?= empty($email_err) ? '' : 'is-invalid' ?>" size="20" value="<?= htmlspecialchars( $email )?>" autofocus>
						<div class="invalid-feedback"><?= $email_err ?></div>
					</div>
					<div class="form-group">
						<label for="password">Contraseña</label>
						<a class="form-sublink" href="">¿Olvidó su contraseña?</a>
						<input type="text" name="password" class="form-control form-control-lg <?= empty($password_err) ? '' : 'is-invalid' ?>" size="20">
						<div class="invalid-feedback"><?= $password_err ?></div>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-block btn-success mb-4">Ingresar</button>
					</div>
				</form>
				<p class="small text-center text-muted">¿Aún no tienes una cuenta? <a href="/signup-form.php">Regístrate</a></p>
			</div>
		</div>
	</div>
</section>