<section class="my-4">
	<div class="row">
		<div class="col-md-4 offset-md-4">
			<h2 class="mb-3 text-center font-weight-normal">Iniciar sesión</h2>
			<form action="" method="" id="singin-form">
				<div class="form-group">
					<label for="username">Username</label>
					<input type="text" name="username" id="username" class="form-control" autofocus>
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input type="password" name="password" id="password" class="form-control" autofocus>
				</div>
				<button type="submit" class="btn btn-success btn-block">Send</button>
			</form>
		</div>
	</div>
</section>